name: Data Refresh

on: [push, pull_request]
 # schedule:
 #   - cron:  '0 */8 * * *'
jobs:
  data refresh test:
    name: Data refresh test
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/covid19rdata:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'rami-dev'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install Github packages
        run: Rscript -e "devtools::load_all(); acquire_data()"
      - name: Push updates 
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git add data-raw/*
              git commit -m "Auto-update" 
              git push
          fi
