name: Data Refresh

on:
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  build:
    name: Data refresh 
    runs-on: macOS-latest 
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install devtools
        run: Rscript -e "install.packages(c('devtools', 'usethis'))" 
      - name: Install Github packages
        run: Rscript -e "devtools::install_github('Covid19R/covid19Rdata', ref = 'rami-dev')"
      - name: Install Github packages dependencies
        run: Rscript -e "covid19Rdata:::install_depend()"
      - name: Refresh the data 
        run: Rscript -e "covid19Rdata::acquire_data()" 
      - name: Push updates 
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'aedobbyn'
              git config --global user.email 'amanda.e.dobbyn@gmail.com'
              git commit -am "Auto-update"
              git push
          fi
